# Generated by Django 5.1.2 on 2024-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('content', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Превью')),
                ('created_at', models.DateField(null=True)),
                ('sign_of_publication', models.BooleanField()),
                ('number_views', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['heading'],
            },
        ),
    ]
