# Generated by Django 5.1.2 on 2024-12-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='number_views',
            new_name='views_count',
        ),
    ]
